import os

base_dir = r"c:\Users\user\Downloads\UDX (2) 2\UDX (2)\android_app\app\src\main\res"

languages = {
    "": { # Default (English)
        "app_name": "UDX",
        "cancel": "Cancel",
        "confirm": "Confirm",
        "retry": "Retry",
        "phone_number": "Phone Number",
        "password": "Password",
        "login": "Login",
        "sign_in_google": "Sign in with Google",
        "dont_have_account": "Don't have an account? Register",
        "full_name": "Full Name",
        "buyer": "Buyer",
        "seller": "Seller",
        "register": "Register",
        "register_google": "Register with Google",
        "already_have_account": "Already have an account? Login",
        "marketplace": "Marketplace",
        "search_products": "Search products... (@nickname, name, phone)",
        "weather": "Weather",
        "partly_cloudy": "Partly Cloudy",
        "analytics": "Analytics",
        "market_trends": "Market Trends",
        "all_categories": "All Categories",
        "your_balance": "Your Balance",
        "fill_balance": "+ Fill",
        "withdraw": "Withdraw",
        "two_factor_auth": "Two-Factor Authentication",
        "app_version": "App Version",
        "log_out": "Log Out",
        "amount": "Amount ($)",
        "add_new_product": "Add New Product",
        "product_name": "Product Name",
        "price": "Price ($)",
        "unit": "Unit (e.g., kg, ton)",
        "description": "Description",
        "category": "Category",
        "select_image": "Select Image",
        "create_product": "Create Product",
        "fill_all_fields": "Please fill all fields and select an image",
        "product_added_success": "Product added successfully!",
        "failed_add_product": "Failed to add product",
        "contracts": "Contracts",
        "search_contracts": "Search contracts...",
        "no_contracts_found": "No contracts found",
        "real_time_market_data": "Real-time agricultural market data",
        "latest_price_data": "Latest price data",
        "price_history": "Price History",
        "no_history_data": "No history data available",
        "market_insights": "Market Insights",
        "all_time_high": "All-time High",
        "all_time_low": "All-time Low",
        "average_price": "Average Price",
        "message": "Message...",
        "messages": "Messages",
        "guest_user": "Guest User",
        "guest_mode": "Guest Mode",
        "account_security": "Account &amp; Security",
        "edit_profile": "Edit Profile",
        "edit_profile_sub": "Name, company, contacts",
        "not_set": "Not set",
        "change_password": "Change Password",
        "payment_details": "Payment Details",
        "payment_details_sub": "Manage cards and methods",
        "notifications": "Notifications",
        "push_notifications": "Push Notifications",
        "messages_from_sellers": "Messages from Sellers",
        "price_changes_orders": "Price Changes &amp; Orders",
        "market_news_analytics": "Market News &amp; Analytics",
        "system_notifications": "System Notifications",
        "privacy": "Privacy",
        "profile_visibility": "Profile Visibility",
        "profile_visibility_sub": "All users",
        "preferences": "Preferences",
        "language": "Language",
        "units_of_measurement": "Units of Measurement",
        "currency": "Currency",
        "product_search_region": "Product Search Region",
        "current_location": "Current location",
        "about_app": "About the App",
        "help_support": "Help &amp; Support",
        "terms_use": "Terms of Use",
        "privacy_policy": "Privacy Policy",
        "language_en": "English",
        "language_es": "Español",
        "language_fr": "Français",
        "language_de": "Deutsch",
        "language_ru": "Русский",
        "language_uz": "O'zbek",
        "language_kk": "Қазақ",
        "language_ky": "Кыргызча",
        "language_tg": "Тоҷикӣ"
    },
    "-es": {
        "app_name": "UDX",
        "cancel": "Cancelar",
        "confirm": "Confirmar",
        "retry": "Reintentar",
        "phone_number": "Número de Teléfono",
        "password": "Contraseña",
        "login": "Iniciar sesión",
        "sign_in_google": "Iniciar sesión con Google",
        "dont_have_account": "¿No tienes cuenta? Regístrate",
        "full_name": "Nombre completo",
        "buyer": "Comprador",
        "seller": "Vendedor",
        "register": "Registrarse",
        "register_google": "Registrarse con Google",
        "already_have_account": "¿Ya tienes cuenta? Inicia sesión",
        "marketplace": "Mercado",
        "search_products": "Buscar productos... (@apodo, nombre, teléfono)",
        "weather": "Clima",
        "partly_cloudy": "Parcialmente nublado",
        "analytics": "Análisis",
        "market_trends": "Tendencias de mercado",
        "all_categories": "Todas las categorías",
        "your_balance": "Tu saldo",
        "fill_balance": "+ Recargar",
        "withdraw": "Retirar",
        "two_factor_auth": "Autenticación de dos factores",
        "app_version": "Versión de la app",
        "log_out": "Cerrar sesión",
        "amount": "Monto ($)",
        "add_new_product": "Agregar nuevo producto",
        "product_name": "Nombre del producto",
        "price": "Precio ($)",
        "unit": "Unidad (ej. kg, ton)",
        "description": "Descripción",
        "category": "Categoría",
        "select_image": "Seleccionar imagen",
        "create_product": "Crear producto",
        "fill_all_fields": "Completa todos los campos y selecciona una imagen",
        "product_added_success": "¡Producto agregado con éxito!",
        "failed_add_product": "Error al agregar producto",
        "contracts": "Contratos",
        "search_contracts": "Buscar contratos...",
        "no_contracts_found": "No se encontraron contratos",
        "real_time_market_data": "Datos de mercado agrícola en tiempo real",
        "latest_price_data": "Últimos precios",
        "price_history": "Historial de precios",
        "no_history_data": "No hay datos de historial",
        "market_insights": "Información de mercado",
        "all_time_high": "Alto histórico",
        "all_time_low": "Bajo histórico",
        "average_price": "Precio promedio",
        "message": "Mensaje...",
        "messages": "Mensajes",
        "guest_user": "Usuario invitado",
        "guest_mode": "Modo invitado",
        "account_security": "Cuenta y Seguridad",
        "edit_profile": "Editar perfil",
        "edit_profile_sub": "Nombre, empresa, contactos",
        "not_set": "No establecido",
        "change_password": "Cambiar Contraseña",
        "payment_details": "Detalles de pago",
        "payment_details_sub": "Administrar tarjetas y métodos",
        "notifications": "Notificaciones",
        "push_notifications": "Notificaciones Push",
        "messages_from_sellers": "Mensajes de vendedores",
        "price_changes_orders": "Cambios de precio y pedidos",
        "market_news_analytics": "Noticias de mercado y análisis",
        "system_notifications": "Notificaciones del sistema",
        "privacy": "Privacidad",
        "profile_visibility": "Visibilidad del perfil",
        "profile_visibility_sub": "Todos los usuarios",
        "preferences": "Preferencias",
        "language": "Idioma",
        "units_of_measurement": "Unidades de medida",
        "currency": "Moneda",
        "product_search_region": "Región de búsqueda de productos",
        "current_location": "Ubicación actual",
        "about_app": "Acerca de la app",
        "help_support": "Ayuda y Soporte",
        "terms_use": "Términos de uso",
        "privacy_policy": "Política de Privacidad",
        "language_en": "English",
        "language_es": "Español",
        "language_fr": "Français",
        "language_de": "Deutsch",
        "language_ru": "Русский",
        "language_uz": "O'zbek",
        "language_kk": "Қазақ",
        "language_ky": "Кыргызча",
        "language_tg": "Тоҷикӣ"
    },
    "-fr": {
        "app_name": "UDX",
        "cancel": "Annuler",
        "confirm": "Confirmer",
        "retry": "Réessayer",
        "phone_number": "Numéro de téléphone",
        "password": "Mot de passe",
        "login": "Se connecter",
        "sign_in_google": "Se connecter avec Google",
        "dont_have_account": "Pas de compte ? S'inscrire",
        "full_name": "Nom complet",
        "buyer": "Acheteur",
        "seller": "Vendeur",
        "register": "S'inscrire",
        "register_google": "S'inscrire avec Google",
        "already_have_account": "Déjà un compte ? Se connecter",
        "marketplace": "Marché",
        "search_products": "Rechercher des produits...",
        "weather": "Météo",
        "partly_cloudy": "Partiellement nuageux",
        "analytics": "Analyses",
        "market_trends": "Tendances du marché",
        "all_categories": "Toutes les catégories",
        "your_balance": "Votre solde",
        "fill_balance": "+ Recharger",
        "withdraw": "Retirer",
        "two_factor_auth": "Authentification à deux facteurs",
        "app_version": "Version de l'application",
        "log_out": "Se déconnecter",
        "amount": "Montant ($)",
        "add_new_product": "Ajouter un produit",
        "product_name": "Nom du produit",
        "price": "Prix ($)",
        "unit": "Unité (ex. kg, tonne)",
        "description": "Description",
        "category": "Catégorie",
        "select_image": "Sélectionner une image",
        "create_product": "Créer le produit",
        "fill_all_fields": "Veuillez remplir tous les champs",
        "product_added_success": "Produit ajouté avec succès!",
        "failed_add_product": "Échec de l'ajout",
        "contracts": "Contrats",
        "search_contracts": "Rechercher des contrats...",
        "no_contracts_found": "Aucun contrat trouvé",
        "real_time_market_data": "Données du marché agricole",
        "latest_price_data": "Derniers prix",
        "price_history": "Historique des prix",
        "no_history_data": "Aucun historique disponible",
        "market_insights": "Aperçu du marché",
        "all_time_high": "Plus haut historique",
        "all_time_low": "Plus bas historique",
        "average_price": "Prix moyen",
        "message": "Message...",
        "messages": "Messages",
        "guest_user": "Invité",
        "guest_mode": "Mode invité",
        "account_security": "Compte et Sécurité",
        "edit_profile": "Modifier le profil",
        "edit_profile_sub": "Nom, entreprise, contacts",
        "not_set": "Non défini",
        "change_password": "Changer le mot de passe",
        "payment_details": "Détails de paiement",
        "payment_details_sub": "Gérer les cartes et méthodes",
        "notifications": "Notifications",
        "push_notifications": "Notifications Push",
        "messages_from_sellers": "Messages des vendeurs",
        "price_changes_orders": "Changements de prix",
        "market_news_analytics": "Actualités du marché",
        "system_notifications": "Notifications système",
        "privacy": "Confidentialité",
        "profile_visibility": "Visibilité du profil",
        "profile_visibility_sub": "Tous les utilisateurs",
        "preferences": "Préférences",
        "language": "Langue",
        "units_of_measurement": "Unités de mesure",
        "currency": "Devise",
        "product_search_region": "Région de recherche",
        "current_location": "Emplacement actuel",
        "about_app": "À propos",
        "help_support": "Aide et Support",
        "terms_use": "Conditions d'utilisation",
        "privacy_policy": "Politique de confidentialité",
        "language_en": "English",
        "language_es": "Español",
        "language_fr": "Français",
        "language_de": "Deutsch",
        "language_ru": "Русский",
        "language_uz": "O'zbek",
        "language_kk": "Қазақ",
        "language_ky": "Кыргызча",
        "language_tg": "Тоҷикӣ"
    },
    "-de": {
        "app_name": "UDX",
        "cancel": "Abbrechen",
        "confirm": "Bestätigen",
        "retry": "Wiederholen",
        "phone_number": "Telefonnummer",
        "password": "Passwort",
        "login": "Anmelden",
        "sign_in_google": "Mit Google anmelden",
        "dont_have_account": "Kein Konto? Registrieren",
        "full_name": "Vollständiger Name",
        "buyer": "Käufer",
        "seller": "Verkäufer",
        "register": "Registrieren",
        "register_google": "Mit Google registrieren",
        "already_have_account": "Bereits ein Konto? Anmelden",
        "marketplace": "Marktplatz",
        "search_products": "Produkte suchen...",
        "weather": "Wetter",
        "partly_cloudy": "Teilweise bewölkt",
        "analytics": "Analytik",
        "market_trends": "Markttrends",
        "all_categories": "Alle Kategorien",
        "your_balance": "Dein Guthaben",
        "fill_balance": "+ Aufladen",
        "withdraw": "Abheben",
        "two_factor_auth": "Zwei-Faktor-Authentifizierung",
        "app_version": "App-Version",
        "log_out": "Abmelden",
        "amount": "Betrag ($)",
        "add_new_product": "Neues Produkt hinzufügen",
        "product_name": "Produktname",
        "price": "Preis ($)",
        "unit": "Einheit (z.B. kg, Tonne)",
        "description": "Beschreibung",
        "category": "Kategorie",
        "select_image": "Bild auswählen",
        "create_product": "Produkt erstellen",
        "fill_all_fields": "Bitte alle Felder ausfüllen",
        "product_added_success": "Produkt erfolgreich hinzugefügt!",
        "failed_add_product": "Fehler beim Hinzufügen",
        "contracts": "Verträge",
        "search_contracts": "Verträge suchen...",
        "no_contracts_found": "Keine Verträge gefunden",
        "real_time_market_data": "Echtzeit-Agrarmarktdaten",
        "latest_price_data": "Aktuelle Preise",
        "price_history": "Preisverlauf",
        "no_history_data": "Keine Verlaufsdaten",
        "market_insights": "Markteinblicke",
        "all_time_high": "Allzeithoch",
        "all_time_low": "Allzeittief",
        "average_price": "Durchschnittspreis",
        "message": "Nachricht...",
        "messages": "Nachrichten",
        "guest_user": "Gastnutzer",
        "guest_mode": "Gastmodus",
        "account_security": "Konto &amp; Sicherheit",
        "edit_profile": "Profil bearbeiten",
        "edit_profile_sub": "Name, Unternehmen, Kontakte",
        "not_set": "Nicht festgelegt",
        "change_password": "Passwort ändern",
        "payment_details": "Zahlungsdetails",
        "payment_details_sub": "Karten und Methoden",
        "notifications": "Benachrichtigungen",
        "push_notifications": "Push-Benachrichtigungen",
        "messages_from_sellers": "Nachrichten von Verkäufern",
        "price_changes_orders": "Preisänderungen",
        "market_news_analytics": "Marktnachrichten",
        "system_notifications": "Systembenachrichtigungen",
        "privacy": "Datenschutz",
        "profile_visibility": "Profilsichtbarkeit",
        "profile_visibility_sub": "Alle Nutzer",
        "preferences": "Präferenzen",
        "language": "Sprache",
        "units_of_measurement": "Maßeinheiten",
        "currency": "Währung",
        "product_search_region": "Produktsuchregion",
        "current_location": "Aktueller Standort",
        "about_app": "Über die App",
        "help_support": "Hilfe &amp; Support",
        "terms_use": "Nutzungsbedingungen",
        "privacy_policy": "Datenschutzrichtlinien",
        "language_en": "English",
        "language_es": "Español",
        "language_fr": "Français",
        "language_de": "Deutsch",
        "language_ru": "Русский",
        "language_uz": "O'zbek",
        "language_kk": "Қазақ",
        "language_ky": "Кыргызча",
        "language_tg": "Тоҷикӣ"
    },
    "-ru": {
        "app_name": "UDX",
        "cancel": "Отмена",
        "confirm": "Подтвердить",
        "retry": "Повторить",
        "phone_number": "Номер телефона",
        "password": "Пароль",
        "login": "Войти",
        "sign_in_google": "Войти через Google",
        "dont_have_account": "Нет аккаунта? Зарегистрируйтесь",
        "full_name": "Полное имя",
        "buyer": "Покупатель",
        "seller": "Продавец",
        "register": "Регистрация",
        "register_google": "Регистрация через Google",
        "already_have_account": "Уже есть аккаунт? Войти",
        "marketplace": "Маркетплейс",
        "search_products": "Поиск продуктов... (@ник, имя, телефон)",
        "weather": "Погода",
        "partly_cloudy": "Переменная облачность",
        "analytics": "Аналитика",
        "market_trends": "Тенденции рынка",
        "all_categories": "Все категории",
        "your_balance": "Ваш баланс",
        "fill_balance": "+ Пополнить",
        "withdraw": "Вывести",
        "two_factor_auth": "Двухфакторная аутентификация",
        "app_version": "Версия приложения",
        "log_out": "Выйти",
        "amount": "Сумма ($)",
        "add_new_product": "Добавить новый продукт",
        "product_name": "Название продукта",
        "price": "Цена ($)",
        "unit": "Единица (например, кг, тонна)",
        "description": "Описание",
        "category": "Категория",
        "select_image": "Выбрать изображение",
        "create_product": "Создать продукт",
        "fill_all_fields": "Пожалуйста, заполните все поля и выберите фото",
        "product_added_success": "Продукт успешно добавлен!",
        "failed_add_product": "Ошибка при добавлении продукта",
        "contracts": "Контракты",
        "search_contracts": "Поиск контрактов...",
        "no_contracts_found": "Контракты не найдены",
        "real_time_market_data": "Данные сельскохозяйственного рынка в реальном времени",
        "latest_price_data": "Последние цены",
        "price_history": "История цен",
        "no_history_data": "Нет данных истории",
        "market_insights": "Анализ рынка",
        "all_time_high": "Исторический максимум",
        "all_time_low": "Исторический минимум",
        "average_price": "Средняя цена",
        "message": "Сообщение...",
        "messages": "Сообщения",
        "guest_user": "Гость",
        "guest_mode": "Гостевой режим",
        "account_security": "Аккаунт и Безопасность",
        "edit_profile": "Редактировать профиль",
        "edit_profile_sub": "Имя, компания, контакты",
        "not_set": "Не задано",
        "change_password": "Изменить пароль",
        "payment_details": "Платежные реквизиты",
        "payment_details_sub": "Управление картами и методами",
        "notifications": "Уведомления",
        "push_notifications": "Push-уведомления",
        "messages_from_sellers": "Сообщения от продавцов",
        "price_changes_orders": "Изменения цен и заказы",
        "market_news_analytics": "Новости рынка и аналитика",
        "system_notifications": "Системные уведомления",
        "privacy": "Конфиденциальность",
        "profile_visibility": "Видимость профиля",
        "profile_visibility_sub": "Все пользователи",
        "preferences": "Настройки",
        "language": "Язык",
        "units_of_measurement": "Единицы измерения",
        "currency": "Валюта",
        "product_search_region": "Регион поиска продуктов",
        "current_location": "Текущее местоположение",
        "about_app": "О приложении",
        "help_support": "Помощь и Поддержка",
        "terms_use": "Условия использования",
        "privacy_policy": "Политика конфиденциальности",
        "language_en": "English",
        "language_es": "Español",
        "language_fr": "Français",
        "language_de": "Deutsch",
        "language_ru": "Русский",
        "language_uz": "O'zbek",
        "language_kk": "Қазақ",
        "language_ky": "Кыргызча",
        "language_tg": "Тоҷикӣ"
    },
    "-uz": {
        "app_name": "UDX",
        "cancel": "Bekor qilish",
        "confirm": "Tasdiqlash",
        "retry": "Qayta urinish",
        "phone_number": "Telefon raqami",
        "password": "Parol",
        "login": "Kirish",
        "sign_in_google": "Google orqali kirish",
        "dont_have_account": "Akkauntingiz yo'qmi? Ro'yxatdan o'ting",
        "full_name": "To'liq ism",
        "buyer": "Xaridor",
        "seller": "Sotuvchi",
        "register": "Ro'yxatdan o'tish",
        "register_google": "Google orqali ro'yxatdan o'tish",
        "already_have_account": "Akkauntingiz bormi? Kirish",
        "marketplace": "Bozor",
        "search_products": "Mahsulot qidirish...",
        "weather": "Ob-havo",
        "partly_cloudy": "Biroz bulutli",
        "analytics": "Analitika",
        "market_trends": "Bozor tendensiyalari",
        "all_categories": "Barcha kategoriyalar",
        "your_balance": "Sizning balansingiz",
        "fill_balance": "+ To'ldirish",
        "withdraw": "Yechib olish",
        "two_factor_auth": "Ikki faktorli autentifikatsiya",
        "app_version": "Ilova versiyasi",
        "log_out": "Chiqish",
        "amount": "Miqdor ($)",
        "add_new_product": "Yangi mahsulot qo'shish",
        "product_name": "Mahsulot nomi",
        "price": "Narx ($)",
        "unit": "Birlik (masalan, kg, tonna)",
        "description": "Tavsif",
        "category": "Kategoriya",
        "select_image": "Rasm tanlang",
        "create_product": "Mahsulot yaratish",
        "fill_all_fields": "Iltimos, barcha maydonlarni to'ldiring",
        "product_added_success": "Mahsulot muvaffaqiyatli qo'shildi!",
        "failed_add_product": "Mahsulot qo'shishda xatolik",
        "contracts": "Shartnomalar",
        "search_contracts": "Shartnomalarni qidirish...",
        "no_contracts_found": "Shartnomalar topilmadi",
        "real_time_market_data": "Jonli qishloq xo'jaligi bozori ma'lumotlari",
        "latest_price_data": "So'nggi narxlar",
        "price_history": "Narxlar tarixi",
        "no_history_data": "Tarixiy ma'lumotlar yo'q",
        "market_insights": "Bozor haqida ma'lumot",
        "all_time_high": "Tarixdagi eng yuqori",
        "all_time_low": "Tarixdagi eng past",
        "average_price": "O'rtacha narx",
        "message": "Xabar...",
        "messages": "Xabarlar",
        "guest_user": "Mehmon",
        "guest_mode": "Mehmon rejimi",
        "account_security": "Akkaunt va Xavfsizlik",
        "edit_profile": "Profilni tahrirlash",
        "edit_profile_sub": "Ism, kompaniya, kontaktlar",
        "not_set": "O'rnatilmagan",
        "change_password": "Parolni o'zgartirish",
        "payment_details": "To'lov ma'lumotlari",
        "payment_details_sub": "Karta va usullarni boshqarish",
        "notifications": "Bildirishnomalar",
        "push_notifications": "Push bildirishnomalar",
        "messages_from_sellers": "Sotuvchilardan xabarlar",
        "price_changes_orders": "Narx o'zgarishi va buyurtmalar",
        "market_news_analytics": "Bozor yangiliklari va analitika",
        "system_notifications": "Tizim bildirishnomalari",
        "privacy": "Maxfiylik",
        "profile_visibility": "Profil ko'rinishi",
        "profile_visibility_sub": "Barcha foydalanuvchilar",
        "preferences": "Afzalliklar",
        "language": "Til",
        "units_of_measurement": "O'lchov birliklari",
        "currency": "Valyuta",
        "product_search_region": "Mahsulot qidirish hududi",
        "current_location": "Joriy joylashuv",
        "about_app": "Ilova haqida",
        "help_support": "Yordam va qo'llab-quvvatlash",
        "terms_use": "Foydalanish shartlari",
        "privacy_policy": "Maxfiylik siyosati",
        "language_en": "English",
        "language_es": "Español",
        "language_fr": "Français",
        "language_de": "Deutsch",
        "language_ru": "Русский",
        "language_uz": "O'zbek",
        "language_kk": "Қазақ",
        "language_ky": "Кыргызча",
        "language_tg": "Тоҷикӣ"
    },
    "-kk": {
        "app_name": "UDX",
        "cancel": "Болдырмау",
        "confirm": "Растау",
        "retry": "Қайталау",
        "phone_number": "Телефон нөмірі",
        "password": "Құпия сөз",
        "login": "Кіру",
        "sign_in_google": "Google арқылы кіру",
        "dont_have_account": "Аккаунтыңыз жоқ па? Тіркелу",
        "full_name": "Толық аты",
        "buyer": "Сатып алушы",
        "seller": "Сатушы",
        "register": "Тіркелу",
        "register_google": "Google арқылы тіркелу",
        "already_have_account": "Аккаунтыңыз бар ма? Кіру",
        "marketplace": "Маркетплейс",
        "search_products": "Өнімдерді іздеу...",
        "weather": "Ауа райы",
        "partly_cloudy": "Аздап бұлтты",
        "analytics": "Аналитика",
        "market_trends": "Нарық трендтері",
        "all_categories": "Барлық категориялар",
        "your_balance": "Сіздің балансыңыз",
        "fill_balance": "+ Толықтыру",
        "withdraw": "Шығару",
        "two_factor_auth": "Екі факторлы аутентификация",
        "app_version": "Қолданба нұсқасы",
        "log_out": "Шығу",
        "amount": "Сома ($)",
        "add_new_product": "Жаңа өнім қосу",
        "product_name": "Өнім атауы",
        "price": "Баға ($)",
        "unit": "Бірлік (мысалы, кг, тонна)",
        "description": "Сипаттама",
        "category": "Категория",
        "select_image": "Суретті таңдау",
        "create_product": "Өнімді жасау",
        "fill_all_fields": "Барлық өрістерді толтырыңыз",
        "product_added_success": "Өнім сәтті қосылды!",
        "failed_add_product": "Өнімді қосу сәтсіз аяқталды",
        "contracts": "Келісімшарттар",
        "search_contracts": "Келісімшарттарды іздеу...",
        "no_contracts_found": "Келісімшарттар табылмады",
        "real_time_market_data": "Нақты уақыттағы ауыл шаруашылығы нарығы",
        "latest_price_data": "Соңғы бағалар",
        "price_history": "Баға тарихы",
        "no_history_data": "Тарих деректері жоқ",
        "market_insights": "Нарық туралы түсінік",
        "all_time_high": "Тарихи максимум",
        "all_time_low": "Тарихи минимум",
        "average_price": "Орташа баға",
        "message": "Хабарлама...",
        "messages": "Хабарламалар",
        "guest_user": "Қонақ",
        "guest_mode": "Қонақ режимі",
        "account_security": "Аккаунт және Қауіпсіздік",
        "edit_profile": "Профильді өңдеу",
        "edit_profile_sub": "Аты, компания, контактілер",
        "not_set": "Орнатылмаған",
        "change_password": "Құпия сөзді өзгерту",
        "payment_details": "Төлем мәліметтері",
        "payment_details_sub": "Карталарды және әдістерді басқару",
        "notifications": "Хабарландырулар",
        "push_notifications": "Push-хабарландырулар",
        "messages_from_sellers": "Сатушылардан хабарламалар",
        "price_changes_orders": "Баға өзгерістері және тапсырыстар",
        "market_news_analytics": "Нарық жаңалықтары мен аналитика",
        "system_notifications": "Жүйелік хабарландырулар",
        "privacy": "Құпиялылық",
        "profile_visibility": "Профильдің көрінуі",
        "profile_visibility_sub": "Барлық пайдаланушылар",
        "preferences": "Баптаулар",
        "language": "Тіл",
        "units_of_measurement": "Өлшем бірліктері",
        "currency": "Валюта",
        "product_search_region": "Өнім іздеу аймағы",
        "current_location": "Ағымдағы орын",
        "about_app": "Қолданба туралы",
        "help_support": "Көмек және Қолдау",
        "terms_use": "Пайдалану шарттары",
        "privacy_policy": "Құпиялылық саясаты",
        "language_en": "English",
        "language_es": "Español",
        "language_fr": "Français",
        "language_de": "Deutsch",
        "language_ru": "Русский",
        "language_uz": "O'zbek",
        "language_kk": "Қазақ",
        "language_ky": "Кыргызча",
        "language_tg": "Тоҷикӣ"
    },
    "-ky": {
        "app_name": "UDX",
        "cancel": "Жокко чыгаруу",
        "confirm": "Тактоо",
        "retry": "Кайталоо",
        "phone_number": "Телефон номери",
        "password": "Сыр сөз",
        "login": "Кирүү",
        "sign_in_google": "Google аркылуу кирүү",
        "dont_have_account": "Аккаунтуңуз жокпу? Каттоо",
        "full_name": "Толук аты",
        "buyer": "Сатып алуучу",
        "seller": "Сатуучу",
        "register": "Каттоо",
        "register_google": "Google аркылуу каттоо",
        "already_have_account": "Аккаунтуңуз барбы? Кирүү",
        "marketplace": "Маркетплейс",
        "search_products": "Продукцияларды издөө...",
        "weather": "Аба ырайы",
        "partly_cloudy": "Бир аз булуттуу",
        "analytics": "Аналитика",
        "market_trends": "Базар тренддери",
        "all_categories": "Бардык категориялар",
        "your_balance": "Сиздин балансыңыз",
        "fill_balance": "+ Толуктоо",
        "withdraw": "Чыгаруу",
        "two_factor_auth": "Эки факторлуу аутентификация",
        "app_version": "Тиркеме версиясы",
        "log_out": "Чыгуу",
        "amount": "Сумма ($)",
        "add_new_product": "Жаңы продукт кошуу",
        "product_name": "Продукттун аты",
        "price": "Баасы ($)",
        "unit": "Бирдик (мисалы, кг, тонна)",
        "description": "Баяндоо",
        "category": "Категория",
        "select_image": "Сүрөт тандоо",
        "create_product": "Продукт түзүү",
        "fill_all_fields": "Бардык талааларды толтуруңуз",
        "product_added_success": "Продукт ийгиликтүү кошулду!",
        "failed_add_product": "Продукт кошуу ишке ашкан жок",
        "contracts": "Келишимдер",
        "search_contracts": "Келишимдерди издөө...",
        "no_contracts_found": "Келишимдер табылган жок",
        "real_time_market_data": "Реалдуу убакыттагы айыл чарба базар маалыматтары",
        "latest_price_data": "Соңку баалар",
        "price_history": "Баалардын тарыхы",
        "no_history_data": "Тарых маалыматы жок",
        "market_insights": "Базар жөнүндө маалымат",
        "all_time_high": "Тарыхый максимум",
        "all_time_low": "Тарыхый минимум",
        "average_price": "Орточо баа",
        "message": "Кабар...",
        "messages": "Кабарлар",
        "guest_user": "Конок",
        "guest_mode": "Конок режими",
        "account_security": "Аккаунт жана Коопсуздук",
        "edit_profile": "Профилди түзөтүү",
        "edit_profile_sub": "Аты, компания, байланыштар",
        "not_set": "Орнотулган жок",
        "change_password": "Сыр сөздү өзгөртүү",
        "payment_details": "Төлөм чоо-жайы",
        "payment_details_sub": "Карталарды жана ыкмаларды башкаруу",
        "notifications": "Кабарландыруулар",
        "push_notifications": "Push-кабарландыруулар",
        "messages_from_sellers": "Сатуучулардан кабарлар",
        "price_changes_orders": "Баалардын өзгөрүшү жана буйрутмалар",
        "market_news_analytics": "Базар жаңылыктары жана аналитика",
        "system_notifications": "Системалык кабарландыруулар",
        "privacy": "Купуялык",
        "profile_visibility": "Профилдин көрүнүүсү",
        "profile_visibility_sub": "Бардык колдонуучулар",
        "preferences": "Өзгөчөлүктөр",
        "language": "Тил",
        "units_of_measurement": "Өлчөө бирдиктери",
        "currency": "Валюта",
        "product_search_region": "Продукт издөө аймагы",
        "current_location": "Учурдагы жайгашкан жер",
        "about_app": "Тиркеме жөнүндө",
        "help_support": "Жардам жана Колдоо",
        "terms_use": "Колдонуу шарттары",
        "privacy_policy": "Купуялык саясаты",
        "language_en": "English",
        "language_es": "Español",
        "language_fr": "Français",
        "language_de": "Deutsch",
        "language_ru": "Русский",
        "language_uz": "O'zbek",
        "language_kk": "Қазақ",
        "language_ky": "Кыргызча",
        "language_tg": "Тоҷикӣ"
    },
    "-tg": {
        "app_name": "UDX",
        "cancel": "Бекор кардан",
        "confirm": "Тасдиқ кардан",
        "retry": "Аз нав кӯшиш кардан",
        "phone_number": "Рақами телефон",
        "password": "Рамз",
        "login": "Вуруд",
        "sign_in_google": "Вуруд бо Google",
        "dont_have_account": "Аккаунт надоред? Сабти ном",
        "full_name": "Номи пурра",
        "buyer": "Харидор",
        "seller": "Фурӯшанда",
        "register": "Сабти ном",
        "register_google": "Сабти ном бо Google",
        "already_have_account": "Аккаунт доред? Вуруд",
        "marketplace": "Бозор",
        "search_products": "Ҷустуҷӯи маҳсулот...",
        "weather": "Обу ҳаво",
        "partly_cloudy": "Қисман абрнок",
        "analytics": "Таҳлилҳо",
        "market_trends": "Тамоюлҳои бозор",
        "all_categories": "Ҳамаи категорияҳо",
        "your_balance": "Тавозуни шумо",
        "fill_balance": "+ Пур кардан",
        "withdraw": "Бозпас гирифтан",
        "two_factor_auth": "Тасдиқи думарҳилагӣ",
        "app_version": "Версияи барнома",
        "log_out": "Хуруҷ",
        "amount": "Маблағ ($)",
        "add_new_product": "Иловаи маҳсулоти нав",
        "product_name": "Номи маҳсулот",
        "price": "Нарх ($)",
        "unit": "Воҳид (масалан, кг, тонна)",
        "description": "Тавсиф",
        "category": "Категория",
        "select_image": "Интихоби расм",
        "create_product": "Эҷоди маҳсулот",
        "fill_all_fields": "Лутфан ҳамаи майдонҳоро пур кунед",
        "product_added_success": "Маҳсулот бомуваффақият илова шуд!",
        "failed_add_product": "Иловаи маҳсулот ноком шуд",
        "contracts": "Шартномаҳо",
        "search_contracts": "Ҷустуҷӯи шартномаҳо...",
        "no_contracts_found": "Шартномаҳо ёфт нашуданд",
        "real_time_market_data": "Маълумоти бозори кишоварзӣ дар вақти воқеӣ",
        "latest_price_data": "Нархҳои охирин",
        "price_history": "Таърихи нархҳо",
        "no_history_data": "Маълумоти таърихӣ нест",
        "market_insights": "Маълумоти бозор",
        "all_time_high": "Баландтарин дар таърих",
        "all_time_low": "Пасттарин дар таърих",
        "average_price": "Нархи миёна",
        "message": "Паём...",
        "messages": "Паёмҳо",
        "guest_user": "Меҳмон",
        "guest_mode": "Ҳолати меҳмон",
        "account_security": "Ҳисоб ва Амният",
        "edit_profile": "Таҳрири профил",
        "edit_profile_sub": "Ном, ширкат, тамосҳо",
        "not_set": "Танзим нашудааст",
        "change_password": "Тағйири рамз",
        "payment_details": "Тафсилоти пардохт",
        "payment_details_sub": "Идораи кортҳо ва усулҳо",
        "notifications": "Огоҳиномаҳо",
        "push_notifications": "Огоҳиномаҳои Push",
        "messages_from_sellers": "Паёмҳо аз фурӯшандагон",
        "price_changes_orders": "Тағйирёбии нарх ва фармоишҳо",
        "market_news_analytics": "Ахбори бозор ва таҳлилҳо",
        "system_notifications": "Огоҳиномаҳои система",
        "privacy": "Махфият",
        "profile_visibility": "Аёнияти профил",
        "profile_visibility_sub": "Ҳамаи истифодабарандагон",
        "preferences": "Танзимот",
        "language": "Забон",
        "units_of_measurement": "Воҳидҳои ченак",
        "currency": "Асъор",
        "product_search_region": "Минтақаи ҷустуҷӯи маҳсулот",
        "current_location": "Ҷойгиршавии кунунӣ",
        "about_app": "Дар бораи барнома",
        "help_support": "Кӯмак ва Дастгирӣ",
        "terms_use": "Шартҳои истифода",
        "privacy_policy": "Сиёсати махфият",
        "language_en": "English",
        "language_es": "Español",
        "language_fr": "Français",
        "language_de": "Deutsch",
        "language_ru": "Русский",
        "language_uz": "O'zbek",
        "language_kk": "Қазақ",
        "language_ky": "Кыргызча",
        "language_tg": "Тоҷикӣ"
    }
}

for lang_ext, strings in languages.items():
    folder_path = os.path.join(base_dir, f"values{lang_ext}")
    os.makedirs(folder_path, exist_ok=True)
    file_path = os.path.join(folder_path, "strings.xml")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write('<?xml version="1.0" encoding="utf-8"?>\n')
        f.write('<resources>\n')
        for key, value in strings.items():
            # escape single quotes
            valueStr = value.replace("'", "\\'")
            # escape ampersands if they aren't already
            if "&" in valueStr and "&amp;" not in valueStr:
                valueStr = valueStr.replace("&", "&amp;")
            f.write(f'    <string name="{key}">{valueStr}</string>\n')
        f.write('</resources>\n')

print("Successfully generated all strings.xml files.")
